loop over files, ignore exit codes

diff --git a/.github/workflows/tofu-apply.yml b/.github/workflows/tofu-apply.yml
--- a/.github/workflows/tofu-apply.yml
+++ b/.github/workflows/tofu-apply.yml
@@ -170,10 +170,6 @@ jobs:
           echo "Building tofu plan for environment: ${{ github.event.repository.name }}/$ENVIRONMENT"
           cd ${{ matrix.environment }}
           tofu plan -input=false -out=tfplan 2>&1 | tee plan.txt
-          exit_code=${PIPESTATUS[0]}
-          echo "Exit code: $exit_code"
-          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
-
           tofu show -json tfplan > tfplan.json
 
       - name: Check OpenTofu Plan for changes
@@ -192,26 +188,31 @@ jobs:
       - name: Apply OpenTofu plan
         id: tofu-apply
         if: steps.tofu-check-plan.outputs.changes == 'true'
-        continue-on-error: true
         run: |
           echo "Running tofu apply for environment: $ENVIRONMENT"
           cd ${{ matrix.environment }}
           tofu apply tfplan 2>&1 | tee apply.txt
-          exit_code=${PIPESTATUS[0]}
 
           echo "Finished processing environment: $ENVIRONMENT"
-          echo "Exit code: $exit_code"
-          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
 
       - name: Analyse tofu errors
         id: tofu-errors
-        if: ${{ (steps.tofu-plan.outputs.exit_code || '0') != '0' || (steps.tofu-apply.outputs.exit_code || '0') != '0' }}
+        if: always()
         run: |
-          echo "AWS permissions that GitHub Actions is currently lacking:"
           cd ${{ matrix.environment }}
-          cat plan.txt apply.txt 2>/dev/null | \
-            sed -n 's/.*is not authorized to perform: \([^ ]*\).*/\1/p' | \
-            sort -u | sed 's/^/  - /'
 
+          errors=$(for file in plan.txt apply.txt; do
+            if [[ -f "$file" ]]; then
+              sed -n 's/.*is not authorized to perform: \([^ ]*\).*/\1/p' "$file"
+            fi
+          done | sort -u)
+
+          if ! [[ -n "$errors" ]]; then
+            echo "No tofu permission errors to report."
+            exit 0
+          fi
+
+          echo "AWS permissions that GitHub Actions is currently lacking:"
+          echo "$errors" | sed 's/^/  - /'
           echo "If these are expected, please add them to estate-config/tofu/development/iam_actions.yml"
           exit 1
